---

- name: Add the RabbitMQ release signing key to the apt trusted keys
  apt_key: keyserver=hkps.pool.sks-keyservers.net
           id=0x6B73A36E6026DFCA
           state=present

- name: Add the RabbitMQ repository to the apt sources list
  apt_repository: repo='deb https://dl.bintray.com/rabbitmq/debian bionic main'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install RabbitMQ server
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - rabbitmq-server

- name: Enable the RabbitMQ Management Console
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify: restart rabbitmq-server

- name: Make sure rabbitmq-server is enabled and running
  service:
    name: rabbitmq-server
    state: started
    enabled: true

- include: setup_vhosts.yml

- include: setup_users.yml

- name: Ensure that the RabbitMQ service is running
  service: name=rabbitmq-server state=started enabled=yes