---

- name: Install additional packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    #- libav-tools
    - libcurl4-gnutls-dev
    - gnutls-dev
    - libpq-dev
    - "{{ virtualenv_python_version + '-dev' }}"
